### ISSUE TITLE
Style the Balance Container

### ISSUE THREAD

**Issue by savio591** [savio591/dualbank#16]
## Todo

- [x] Title
- [x] Option buttons(Create the type in component button and put in this container)

**Balance Card**

- [x] Date balance button
- [x] UpdatedAt/refresh button
- [x] Balance div + show/hide button
