### ISSUE TITLE
Style the download container

### ISSUE THREAD

**Issue by savio591** [savio591/dualbank#17]
## Todo:

- [x] Container
- [x] Status text
- [x] Status icon
- [x] Separator
- [x] Name of file text
- [x] Play/Pause button
- [x] Right side of container: Cancel Button
