### ISSUE TITLE
Create the component "Dashboard Container"

### ISSUE THREAD

**Issue by savio591** [savio591/dualbank#7]
## Todo
* [x] Cash container:
  * [x] Row 1:
    * [x] Title
    * [x] Print button
    * [x] Download as pdf button
    * [x] Share Button
  
  * [x] Row 2: 
    * [x] Card:
      * [x] Row 1: Date select button with a label about the date of a cash available plus at date select indicator at the right
      * [x] Row 2: Line break with border
      * [x] Row 3: Updated at indicator of time of requested cash value
      * [x] Row 4: Available cash with label and fast hider value at right
