### ISSUE TITLE
Modular Buttons - Create all button types

### ISSUE THREAD

**Issue by savio591** [savio591/dualbank#8]
PS: Create when the component styles are to be created
These buttons will be modulated, calls types and other specs via React Props.

## Todo
**Sidebar button system:**
* [x] Default
* [x] Inactive
* [x] Selected
* [x] Hover
* [x] Arrow Show

**Header Buttons:**
* [x] Copy
* [x] Eye
* [x] Account
* [x] Search
* [x] Apps Popups
* [x] Profile

**Cash by tags bar**
* [x] Tags

**Balance container**
* [x] Opts buttons
* [x] Opts buttons hovered
* [x] Balance date button
* [x] Balance updatedAt refresh Button
* [x] Balance available button

**Download container**
- [x] Play/Pause
- [x] Cancel
